# Generated by Django 5.2 on 2025-08-08 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='banners/')),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('button_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('for_mobile', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('is_active', models.BooleanField(default=True)),
                ('for_mobile', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='home_components/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_components', to='products.category')),
            ],
            options={
                'verbose_name': 'Homepage Component',
                'verbose_name_plural': 'Homepage Components',
            },
        ),
    ]
