# Generated by Django 5.2 on 2025-07-26 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text="Name of the vendor's company.", max_length=255)),
                ('contact_person_name', models.CharField(help_text='Name of the primary contact person.', max_length=255)),
                ('email', models.EmailField(help_text="Company's primary email address for communication.", max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text="Company's primary phone number.", max_length=20, null=True)),
                ('address', models.TextField(help_text='Full physical address of the company.')),
                ('business_type', models.CharField(blank=True, help_text='e.g., Retail, Wholesale, Service Provider.', max_length=100)),
                ('website_url', models.URLField(blank=True, help_text="Optional: Company's website URL.", null=True)),
                ('tax_id', models.CharField(blank=True, help_text='Optional: Tax identification number.', max_length=50, null=True)),
                ('vendor_logo', models.ImageField(blank=True, help_text='Upload your company logo.', null=True, upload_to='vendor_logos/')),
                ('nid', models.CharField(blank=True, help_text='National ID number (optional).', max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the vendor application.', max_length=10)),
                ('application_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the application was submitted.')),
                ('approved_date', models.DateTimeField(blank=True, help_text='Date and time when the application was approved.', null=True)),
                ('user', models.OneToOneField(blank=True, help_text='Django User account associated with this vendor (set upon approval).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Application',
                'verbose_name_plural': 'Vendor Applications',
                'ordering': ['-application_date'],
            },
        ),
    ]
