# Generated by Django 5.2 on 2025-07-28 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_vendorprofile_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='address',
            field=models.TextField(help_text='Full physical address of the company.'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='application_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time when the application was submitted.'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='approved_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the application was approved.', null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='business_type',
            field=models.CharField(blank=True, help_text='e.g., Retail, Wholesale, Service Provider.', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='company_name',
            field=models.CharField(help_text="Name of the vendor's company.", max_length=255),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='contact_person_name',
            field=models.CharField(help_text='Name of the primary contact person.', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='email',
            field=models.EmailField(help_text="Company's primary email address for communication.", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='nid',
            field=models.CharField(blank=True, help_text='National ID number (optional).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Company's primary phone number.", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the vendor application.', max_length=10),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Optional: Tax identification number.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Django User account associated with this vendor (set upon approval).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_logo',
            field=models.ImageField(blank=True, help_text='Upload your company logo.', null=True, upload_to='vendor_logos/'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='website_url',
            field=models.URLField(blank=True, help_text="Optional: Company's website URL.", null=True),
        ),
    ]
