# Generated by Django 5.2 on 2025-08-04 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecommercecheckouts',
            name='items_json',
        ),
        migrations.AddField(
            model_name='ecommercecheckouts',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='ecommercecheckouts',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='processing', max_length=255),
        ),
        migrations.AlterField(
            model_name='ecommercecheckouts',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='VendorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(default=list)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(default='processing', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ecommerce_checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_orders', to='orders.ecommercecheckouts')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
