# Generated by Django 5.2 on 2025-08-04 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_ecommercecheckouts_items_json_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecommercecheckouts',
            old_name='items',
            new_name='items_json',
        ),
        migrations.RenameField(
            model_name='vendororder',
            old_name='items',
            new_name='items_json',
        ),
    ]
