# Generated by Django 5.2 on 2025-07-11 13:20

import autoslug.fields
import products.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_deliverycharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', slugify=products.models.custom_slugify, unique=True),
        ),
    ]
