# Generated by Django 5.2 on 2025-08-02 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_productapplication_product_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
