# Generated by Django 5.2 on 2025-08-02 17:33

import autoslug.fields
import ckeditor.fields
import django.core.validators
import django.db.models.deletion
import products.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_productapplication_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='application',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor_price',
        ),
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', slugify=products.models.custom_slugify, unique=True)),
                ('short_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('product_type', models.CharField(blank=True, choices=[('simple', 'Simple'), ('variable', 'Variable')], default='simple', max_length=20, null=True)),
                ('regular_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('vendor_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('stock_quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='Is the product visible to customers?', null=True)),
                ('is_featured', models.BooleanField(blank=True, default=False, help_text='Should this product be highlighted?', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status: pending, approved, or rejected', max_length=20)),
                ('seo_title', models.CharField(blank=True, help_text='SEO Title for search engines (max 60-70 chars).', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Meta Description for search engines (max 150-160 chars).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='vendor_products', to='products.category')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ProductApplication',
        ),
    ]
