# Generated by Django 5.2 on 2025-08-02 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_product_application_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.vendorproduct')),
            ],
        ),
        migrations.CreateModel(
            name='VendorProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vendor_product_images/%Y/%m/')),
                ('name', models.CharField(blank=True, help_text="A unique name for this image within the product (e.g., 'front_view', 'detail_shot').", max_length=255, null=True)),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility and SEO.', max_length=255, null=True)),
                ('is_featured', models.BooleanField(blank=True, default=False, help_text='Mark as the main image for the product.', null=True)),
                ('order', models.PositiveIntegerField(blank=True, default=0, help_text='Order in which images should appear.', null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='products.vendorproduct')),
            ],
            options={
                'ordering': ['order', '-is_featured'],
                'unique_together': {('product', 'name')},
            },
        ),
    ]
